#!/usr/bin/perl

use POSIX;

my $bucketSize = shift @ARGV;

my %map;
while(<>) {
    chomp;
    my $value = $_;
    if($bucketSize) {
        $value = ceil($value/$bucketSize) * $bucketSize;
    }
    ++$map{$value};
}

for my $key (sort {$a <=> $b} keys %map) {
    print join("\t",$key,$map{$key})."\n";
}
